### PR TITLE
Adding RXE segment support

### PR DESCRIPTION
**Pull request by krengarajan**
Great Library for parsing HL7 messages. Adding support for parsing RXE segement ( Pharamacy encoded order).

### CODE REVIEW

**Comment by Loksly** [comment]
It seems to me some of the fields have the name changed:
https://www.interfaceware.com/hl7-standard/hl7-segment-RXE.html

Those that have ' apostrophe symbol like "Provider's Administration Instructions" or "Pharmacist/Treatment Supplier's Verifier ID", would you please resend this PR with it changed?

If you cannot I can accept it and update it for you.

thanks again for your contribution.

**Comment by Loksly** [comment]
@krengarajan I've just release the 0.2.0 version. Now it's easier to add support to new segments. Please check the new code and add your RXE segment. If you don't have time I'll add on my own in a couple of days.

**Comment by krengarajan** [comment]
Thanks a lot. This package is great. 

    On Monday, November 6, 2017 12:09 PM, M Loksly <notifications@github.com> wrote:
 

 Closed #1.—

**Comment by krengarajan** [comment]
I will add RXE and RXA segments

**Pull request closed without merging**
